package main

import (
    "fmt"
    "github.com/carbocation/rosalind.git/rosalind"
)

func main() {
	ProblemsDna()
}

func ProblemsDna() {
    s := "TGCTTAATTATAGTCTTTCGTACGACGCATGAAGACGCCGGAACTGAAGCGACGCCGTGGTTGATCGTGGCCCCAGAGGTCCATTCCTTTACACCGATGGACAGTCCTAATGTTACTGCGCCCAAGCAAGGGCAGGCGACCTCAGATTCAACCACTAGGGAAGTTCCTTGAACTCATCGTCTAATCGGTGAGTGACGGTAGCCTCCACAGTTGAAATAATCCAGCCTCGAATGCTAGACCACGCGGTCATGATATCTGGGCGTAGCTGTGATCGGAAGTATATAGGTAGACCAGGTTAGCTGAGTGGACCGGGGTCTTCAACATCGGTGACTGGGCAGGTGTACAGAAAACCGCCTCCTAGGTACCTGACTCTTTGCGAAAAAATGCTGGATGTGGGGTACCTCAATACGCTGCGGGAAACCACAACCTCCATCGATTCAAGCAAATGCGGGTCAGATCCACCAGAGTAAAACTTGCATGTAGTCGGCTTTGACCCTGTACAAATATGCTTCGGCCATAGTCCACAACGCACCCAAAGGCTACTCCGGGATAGTGTCTCAACACTACTACTTCTCACTATGGGGATAAATATTCTCTGTTCTCCCTCGCGCTCGCGGATCTTCTACGCGCCCTGTGCGCTCCGGTGGCGCGGCGCATACACCCTCTATCCGTCGACCAATCGATCTCCGCCGTGCTTTTTTGTATCTGTGCATGTCTTTAGTACGGCTTGCCCACACAGCTTGGTCCAAACCCTTGAGTCCCAACTATCACAACGGCGGTAAGTTTCCCCTACTCAGTGTCGCTCCACGGTAGTCTGCTCCCCGTGCCCGCTTCGACGGAGACGGTGAGTACTTCCGCCCATGCGCATCGTGGACGAAACC"

    out := rosalind.CountBases(s)

    fmt.Println(out["A"], out["C"], out["G"], out["T"])
}