package main

import (
    "fmt"
    "github.com/carbocation/rosalind.git/rosalind"
)

func main() {
	ProblemsDna()
    TranscribeDna()
}

func ProblemsDna() {
    s := "TGCTTAATTATAGTCTTTCGTACGACGCATGAAGACGCCGGAACTGAAGCGACGCCGTGGTTGATCGTGGCCCCAGAGGTCCATTCCTTTACACCGATGGACAGTCCTAATGTTACTGCGCCCAAGCAAGGGCAGGCGACCTCAGATTCAACCACTAGGGAAGTTCCTTGAACTCATCGTCTAATCGGTGAGTGACGGTAGCCTCCACAGTTGAAATAATCCAGCCTCGAATGCTAGACCACGCGGTCATGATATCTGGGCGTAGCTGTGATCGGAAGTATATAGGTAGACCAGGTTAGCTGAGTGGACCGGGGTCTTCAACATCGGTGACTGGGCAGGTGTACAGAAAACCGCCTCCTAGGTACCTGACTCTTTGCGAAAAAATGCTGGATGTGGGGTACCTCAATACGCTGCGGGAAACCACAACCTCCATCGATTCAAGCAAATGCGGGTCAGATCCACCAGAGTAAAACTTGCATGTAGTCGGCTTTGACCCTGTACAAATATGCTTCGGCCATAGTCCACAACGCACCCAAAGGCTACTCCGGGATAGTGTCTCAACACTACTACTTCTCACTATGGGGATAAATATTCTCTGTTCTCCCTCGCGCTCGCGGATCTTCTACGCGCCCTGTGCGCTCCGGTGGCGCGGCGCATACACCCTCTATCCGTCGACCAATCGATCTCCGCCGTGCTTTTTTGTATCTGTGCATGTCTTTAGTACGGCTTGCCCACACAGCTTGGTCCAAACCCTTGAGTCCCAACTATCACAACGGCGGTAAGTTTCCCCTACTCAGTGTCGCTCCACGGTAGTCTGCTCCCCGTGCCCGCTTCGACGGAGACGGTGAGTACTTCCGCCCATGCGCATCGTGGACGAAACC"

    out := rosalind.CountBases(s)

    fmt.Println(out["A"], out["C"], out["G"], out["T"])
}

func TranscribeDna() {
    in := []byte("GATGGAACTTGACTACGTAAATT")
    out := rosalind.TranscribeDna(in)
    
    fmt.Println(string(in))
    fmt.Println(string(out))
}